backend: 
"  name: git-gateway" 
"  branch: master" 
"media_folder: \"static/images\"" 
"public_folder: \"/images\"" 
"collections:" 
"  - name: \"gallery\"" 
"    label: \"Галерея\"" 
"    folder: \"content/gallery\"" 
"    create: true" 
"    slug: \"{{slug}}\"" 
"    fields:" 
"      - {label: \"Название\", name: \"title\", widget: \"string\"}" 
"      - {label: \"Дата\", name: \"date\", widget: \"datetime\"}" 
"      - {label: \"Фото\", name: \"image\", widget: \"image\"}" 
"      - {label: \"Описание\", name: \"body\", widget: \"text\"}" 
